# Generated by Django 5.1.4 on 2024-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='librarian',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='librarian',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year in format YYYY-YYYY', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Date of admission', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade or level of the student', max_length=10, null=True),
        ),
    ]
