# Generated by Django 5.1.4 on 2024-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_librarian_address_librarian_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeshistory',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year in format YYYY-YYYY', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='feeshistory',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', help_text='Status of the fee payment', max_length=20),
        ),
        migrations.AddField(
            model_name='libraryhistory',
            name='book_category',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('novel', 'Novel'), ('biography', 'Biography'), ('science', 'Science'), ('history', 'History'), ('others', 'Others')], help_text='Category of the book', max_length=50, null=True),
        ),
    ]
