# Generated by Django 5.1.4 on 2024-12-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feeshistory_academic_year_feeshistory_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='library_section',
        ),
    ]
