# Generated by Django 5.1.4 on 2024-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_librarian_library_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, help_text="Division or section, e.g., 'A', 'B', etc.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(help_text="Class name, e.g., '9th' or '10th'", max_length=50, null=True),
        ),
    ]
